- deps.edn
- org/GridFire.org
- pom.xml
- resources/sample_config.edn
- src/gridfire/cli.clj
- src/gridfire/crown_fire.clj
- src/gridfire/fire_spread.clj
- src/gridfire/fuel_models.clj
- src/gridfire/monte_carlo.clj
- src/gridfire/postgis_bridge.clj
- src/gridfire/surface_fire.clj
Update Magellan version to latest
----
Also Adding support for org-babel-detangle
Related to:
https://github.com/sig-gis/magellan/pull/9
#
> Bump Magellan Fixes#19

- org/GridFire.org
- resources/import-rasters.sh
- resources/sample_config.edn
- src/gridfire/monte_carlo.clj
> adding import rasters section

- deps.edn
- org/GridFire.org
- pom.xml
----
Bump version using chronological versioning
#
> Bump version chronologically

- .github/PULL_REQUEST_TEMPLATE.md
> OPS-30 Add PR Template

- src/gridfire/config.clj
- test/gridfire/config_test.clj
> Extract perturbations from elfmire config

- org/GridFire.org
- src/gridfire/fire_spread.clj
- test/gridfire/cli_test.clj
> refactoring extract content function

- org/GridFire.org
- src/gridfire/fetch.clj
- test/gridfire/cli_test.clj
> Use burn values from config to remap ignition matrix

- org/GridFire.org
- src/gridfire/fire_spread.clj
> Add burn-time matrix

- org/GridFire.org
- src/gridfire/cli.clj
- src/gridfire/fire_spread.clj
- src/gridfire/spec/config.clj
- src/gridfire/spec/output.clj
- test/gridfire/cli_test.clj
- test/gridfire/spec/output_test.clj
> add burn probability matrix and output geotiffs

- org/GridFire.org
- src/gridfire/config.clj
----
Updating Configuration docs. 
Output section now includes controlling output layers
#
> update docs output section

- src/gridfire/spec/config.clj
- test/gridfire/config_test.clj
- test/gridfire/fetch_weather_test.clj
> Misc test fixes

- src/gridfire/spec/config.clj
- src/gridfire/spec/spotting.clj
> Add spec for reading spotting config

- org/GridFire.org
- src/gridfire/spotting.clj
> Add firebrand dispersal formulas

- deps.edn
- org/GridFire.org
- src/gridfire/spotting.clj
- test/gridfire/spotting_test.clj
> Sample firebrand deltas

- org/GridFire.org
- src/gridfire/cli.clj
- src/gridfire/fire_spread.clj
- src/gridfire/spotting.clj
- test/gridfire/spotting_test.clj
> Handle firebrand spread and store count

- org/GridFire.org
- src/gridfire/cli.clj
- src/gridfire/common.clj
- src/gridfire/conversion.clj
- src/gridfire/crown_fire.clj
- src/gridfire/fire_spread.clj
- src/gridfire/spec/config.clj
- src/gridfire/spotting.clj
- Allows Gridfire to identify spot ignitions during the simulation loop
Also done in this PR:
- refactor `gridfire.spotting/spread-firebrands` to use `common.extract-constant` so we can remove `fire-spread/handle-spotting`
1. On gridfire.fire-spread/compute-burn-trajectory: line 129. Convert the the key value pair: 
`:crown-fire? crown-fire?` to `:crown-fire true`
2. Run GridFire with the following config file and look at the spotting behavior by playing through the PNGs
```
{
;; Section 1: Landscape data to be shared by all simulations
:fetch-layer-method :geotiff
:landfire-layers    {:aspect             "test/gridfire/resources/asp.tif"
:canopy-base-height "test/gridfire/resources/cbh.tif"
:canopy-cover       "test/gridfire/resources/cc.tif"
:canopy-height …
```
> Find Spot ignitions

- org/GridFire.org
- src/gridfire/magellan_bridge.clj
> Fixing upperlefty to be the max value of y

- org/GridFire.org
- src/gridfire/cli.clj
- src/gridfire/config.clj
- src/gridfire/spec/output.clj
Adding the ability for users to specify an output directory
> Add output directory

- deps.edn
- src/gridfire/server.clj
- src/gridfire/simple_sockets.clj
- src/gridfire/utils/server.clj
This PR:
- Adds middleman simple sockets code written by @lambdatronic
- adds alias to run a server with a job queue
> Add Server and Middleman Sockets

- org/GridFire.org
- src/gridfire/cli.clj
- src/gridfire/fetch.clj
- src/gridfire/fire_spread.clj
- src/gridfire/spec/config.clj
- src/gridfire/spotting.clj
- src/gridfire/utils/random.clj
> WIP: Refactored gridfire.cli/-main to improve readability and reduce fn args

- deps.edn
- org/GridFire.org
- resources/make_tifs.sh
- resources/postprocess.sh
- src/gridfire/binary_output.clj
- src/gridfire/cli.clj
- src/gridfire/common.clj
- src/gridfire/config.clj
- src/gridfire/fetch.clj
- src/gridfire/fire_spread.clj
- src/gridfire/magellan_bridge.clj
- src/gridfire/perturbation.clj
- src/gridfire/random_ignition.clj
- src/gridfire/server.clj
- src/gridfire/simple_sockets.clj
- src/gridfire/spotting.clj
- test/gridfire/binary_output_test.clj
- test/gridfire/build_test_db.clj
This PR:
- Optimized read-matrices-as-binary
- Removed reflection warnings
- Refactor & optimized random ignition
- Added tufte profiling
- Optimized post processing scripts to use multi thread
> Optimization work done with Gary

- resources/build_geoserver_directory.sh
- resources/cleanup.sh
- resources/elmfire_post.sh
- resources/make_tifs.sh
- resources/upload_tarball.sh
- src/gridfire/binary_output.clj
- src/gridfire/server.clj
- Breaks up postprocess.sh into multiple scripts for better logging
- Send additional progress responses to pyregence
- Added job-queue-size to include place in line in progress response
> Improve logging

- org/GridFire.org
- src/gridfire/fire_spread.clj
Optimization:
- machine: local
- ensemble=10 parllel=None
- tufte point: run-fire-spread
- Before Optimization: 19.06s, 19.49s, 19.96s
- After Optimization: 15.82s, 16.36s, 15.08s
- Result: 20% improvement
Closes GRID-157
> GRID-157 BurnTrajectory record

- org/GridFire.org
- src/gridfire/config.clj
- src/gridfire/fire_spread.clj
When converting elmfire.data to gridfire.edn, change the behavior of calculating
fractional distances to sum
Closes GRID-160
> GRID-160 ELMFIRE conversion: set fractional-distance-combination to sum

- src/gridfire/active_fire_watcher.clj
- src/gridfire/config.clj
- src/gridfire/server.clj
Match Drop runs are prioritized over active fire runs.
> GRID-170 Prioritize match drop over active fire in queue

- resources/build_geoserver_directory.sh
- resources/elmfire_post.sh
- resources/make_tifs.sh
- resources/upload_tarball.sh
Elmfire post process has been updated. 
- Previously burned areas now showing
> GRID-170 Update elmfire post process scripts

- src/gridfire/server.clj
-------
Closes GRID-###
1. Given..., When ..., Then ....
> Fix incorrect spec reference in server.clj

- src/gridfire/server.clj
-------
Closes GRID-###
1. Given..., When ..., Then ....
> Log port when server starts

- deps.edn
- org/GridFire.org
- src/gridfire/cli.clj
- src/gridfire/fire_spread.clj
Removing source of memory leak. Update memoize to reset cache between runs
> Reset memoized cache of rothermel-fast-wrapper between fire runs

- resources/build_geoserver_directory.sh
- resources/cleanup.sh
- resources/elmfire_post.sh
- resources/upload_tarball.sh
Update post processing of binary files to include image mosaic work
Closes GRID-175
#review <comment>`)
> GRID-175  Update postprocess.sh to generate ImageMosaic-compliant output decks
