org/GridFire.org
src/gridfire/cli.clj
src/gridfire/spec/output.clj

----
We are now supporting an output that has these value mappings.
Encoding taken from geotiff served on pyregence
color-map-entry(#000000,   0, 0.0, "nodata")
color-map-entry(#ff0000,   1, 1.0, "1 hour ago")
color-map-entry(#ff9900,   2, 1.0, "2 hours ago")
color-map-entry(#ffff00,   3, 1.0, "3 hours ago")
color-map-entry(#999999,   4, 1.0, "4 hours ago")
color-map-entry(#484848,   5, 0.5, "5+ hours ago")
color-map-entry(#000000, 200, 0.5, "Previously burned")
color-map-entry(#440044, 201, 1.0, "Previous active perimeter");
#

Add burn-history output layer

---

org/GridFire.org
src/gridfire/cli.clj

----
This PR 
- added logic to output layers the final clock time if the keyword `:final` is specified in the config
- added burn_history to output with old logic (when using `:geotiff true` only)
#

Add logic for output layer at simulation end time

---

org/GridFire.org
src/gridfire/spec/spotting.clj
src/gridfire/spotting.clj
test/gridfire/spec/spotting_test.clj

Crown fire spotting percent 
The `:crown-fire-spotting-percent` key is added to the config.edn
under `:spotting`. It controls spotting initiation from passive/active
crown fire pixels, meaning if it is set to 1.0 then 1 out of every 100
pixels that burn as crown fire will initiate the spotting algorithm.

Add crown fire spotting percent

---

org/GridFire.org
src/gridfire/fire_spread.clj
src/gridfire/spec/spotting.clj
src/gridfire/spotting.clj
src/gridfire/utils/random.clj
test/gridfire/spec/spotting_test.clj

The number of firebrands a crown fire ignition event can produce can now be sampled from a range

Allow users to specify num-firebrand range

---

org/GridFire.org
src/gridfire/spec/spotting.clj
src/gridfire/spotting.clj
src/gridfire/utils/random.clj
test/gridfire/spec/spotting_test.clj
test/gridfire/spotting_test.clj

This PR enables surface fires to spot.
- Spec for `:spotting` now includes `:surface-spotting` which contains
a map for surface spotting configurations.
- Added `:spotting-percent` which controls the probability of spot
ignition for specified range of fuel models.

Add surface fire spotting

---

org/GridFire.org
src/gridfire/spec/spotting.clj
src/gridfire/spotting.clj

The critical spotting intensity is the fire line intensity below which
surface fire spotting does not occur.

Add critical spotting intensity

---

org/GridFire.org
src/gridfire/fire_spread.clj

I had came across a divide/zero error when processing a phi.tif with
zero burned cells. This is to catch that and make run-fire-spread
return nil if there are no burnable cells

Check for burnable cells in ignition-layer before running

---

org/GridFire.org
src/gridfire/cli.clj
src/gridfire/fire_spread.clj
test/gridfire/cli_test.clj

- dispatch value ignition-point now changed to ignition-points
- This is will allow both a single ignition point and multiple ignition
points to be handled by the same function.
- Refactor run-fire-spread, pulling out common code

Use random ignition ns in simulation runs

---

org/GridFire.org
src/gridfire/spotting.clj
src/gridfire/utils/random.clj

Perryman's equations are giving us mean and standard deviations that cause the sampling of distances a firebrand can land to be order magnitudes larger than nominal values.
This PR will replace those equations with Elmfire's equations

Replace mean and standard deviation equations with elmfire's

---

resources/build_geoserver_directory.sh
resources/elmfire_post.sh

This PR:
- decreases the number of percentiles from 9 to 5
- disabled generation of spread rate, flame length, and crown fire outputs

Update elmfire_post process to output less results

---

.gitignore
org/GridFire.org
src/gridfire/fire_spread.clj

- converts the representation of ignited-cells 
- Old structure: map of source-cell -> list of neighborhood trajectories
- New structure: list of trajectories
This gave us a 15% improvement in runtime
Optimized 
```
pId                           nCalls        Min        Max       Mean   MAD      Clock  Total
:run-fire-spread                  10     5.02ms     5.80s      2.55s   ±99%    25.53s     96%
:update-ignited-cells          6,011     4.30μs    10.64ms     3.02ms  ±42%    18.14s     68%
:identify-ignition-events      6,011     1.10μs     4.52ms   602.58μs  ±45%     3.62s     14%
:update-matrices               6,011   600.00ns     4.58ms   246.63μs  ±56%     1.48s      6%
:calculate-dt                  6,011   800.00ns     1.03ms   244.55μs  ±52%     1.47s      6%
Accounted …
```

Optimize ignited-cells datastructure

---

org/GridFire.org
src/gridfire/common.clj
src/gridfire/fire_spread.clj
src/gridfire/spotting.clj

Findings: Extract-constants is uncessarily building up a map just to destructure.
Optimization: Instead call sample-at directly in compute-neighborhood-spread-rates 
Optimized Run:
pId                  nCalls        Min        Max       Mean   MAD      Clock  Total
:run-fire-spread         10     4.01ms     4.52s      1.96s   ±99%    19.61s     96%
Accounted                                                             19.61s     96%
Clock                                                                 20.47s    100%
vs
Not Optimized Run:
04/22 10:26:32 Running simulations
04/22 10:26:56 :run-simulation,
pId                  nCalls        Min        Max       Mean   MAD      Clock  Total
:run-fire-spread         10     4.28ms     5.12s      2.24s   ±99%    22.39s     96%
Accounted …

Remove extract-constants and use sample-at

---

org/GridFire.org
src/gridfire/fire_spread.clj
src/gridfire/utils/primitive.clj

ns to test:
- `gridfire.fire-spread`
To test:
1. Start repl

GRID-146 add type hints to fire-spread ns

---

org/GridFire.org
src/gridfire/fuel_models.clj
src/gridfire/surface_fire.clj

ns to test:
- `gridfire.surface-fire`
To test:
1. Start repl

GRID-146 add type hints surface-fire ns

---

org/GridFire.org
src/gridfire/crown_fire.clj

ns to test:
- `gridfire.crown-fire`
To test:
1. Start repl

GRID-146 add type hints crown-fire ns

---

org/GridFire.org
src/gridfire/fuel_models.clj

ns to test:
- `gridfire.fuel-models`
To test:
1. Start repl

GRID-146 add type hints fuel-models ns

---

org/GridFire.org
src/gridfire/conversion.clj
src/gridfire/spotting.clj
src/gridfire/utils/random.clj

ns to test:
- `gridfire.spotting`
To test:
1. Start repl

GRID-146 add type hints spotting ns

---

org/GridFire.org
src/gridfire/common.clj
src/gridfire/conversion.clj
src/gridfire/fire_spread.clj
src/gridfire/perturbation.clj
src/gridfire/utils/random.clj

ns to test:
- `gridfire.conversion`
- `gridfire.fires-spread`
- `gridfire.perturbation`
These ns are only partially type hinted
- `gridfire.random`
To test:
1. Start repl

GRID-146 add type hints misc ns

---

org/GridFire.org
src/gridfire/binary_output.clj
src/gridfire/cli.clj
src/gridfire/fire_spread.clj

mop/- is much slower than mapv. This change gives us ~17% improvement.

GRID-156 replace mop/- with mapv

---

src/gridfire/server.clj

Server Response show's duplicate "GridFire:" label. Pyregence already handles this.
Closes GRID-158

GRID-158 Remove GridFire label on response messages

---

org/GridFire.org
resources/build_geoserver_directory.sh
resources/elmfire_post.sh
resources/upload_tarball.sh
src/gridfire/cli.clj
src/gridfire/common.clj
src/gridfire/config.clj
src/gridfire/conversion.clj
src/gridfire/fire_spread.clj

When comparing GF to ELM misc fixes were identified
Findings:
- Sample-at should return positive values only
- Config conversion
- Perturbations, remove CBH and CBD since ELMFIRE does not implment this
- Landfire Layer: CBD should have multiplier 0.01
- Update upload_tarball.sh to push to /incoming/match_drop directory
- Update build_geoserver.sh to copy imagemosaic_properties.zip
- Add crown fire and spot-count to summary.csv
Closes GRID-159

GRID-159 MISC fixes when comparing GRIDFIRE to ELMFIRE

---

org/GridFire.org
src/gridfire/config.clj
src/gridfire/fire_spread.clj

Currently Gridfire tracks fractional distances coming the 8 possible
trajectories surrounding a cell individually. Therefore there is no cumulative
effect of these trajectories. However according to Morias 2001, at the end of
each time step the fractional distance that all trajectories should use next is
the maximum of the fractional distances calculated in the current time step. 
This work implements this algorithm. Users will have the option to use either
algorithm.
Closes GRID-160

GRID-160 Implementation for fractinoal distance handling according to Morais2001

---

deps.edn
src/gridfire/active_fire_watcher.clj
test/gridfire/active_fire_watcher_test.clj

This PR creates a ns to launch a process watching a specified directory for new
files created. Upon detecting new file, a job entry will be put onto a specified
queue. This process allows us to integrate active fires into the current
match-drop server.
test ns `gridfire.active-fire-watcher-test`

GRID-170 Create active-fire-watcher ns

---

src/gridfire/server.clj
src/gridfire/spec/server.clj

In order to allows active-fire requests to be handled by the server the request
spec needs to be updated so `responseHost` and `responsePort` are optional.

GRID-170 Use active-fire-watcher in server

---

src/gridfire/config.clj

- Add default values when values missing from elmfire.data
- Ignore ignition-mask if file is missing

GRID 170 Elmfire.data conversion misc fixes

---

src/gridfire/active_fire_watcher.clj
src/gridfire/server.clj

For Active fires, we need to send a geosync request to register layers, unlike
match drop which let's pyregence handles it.

GRID-170 Send geosync request to register layer for active fires

---

org/GridFire.org
src/gridfire/cli.clj
src/gridfire/fire_spread.clj
src/gridfire/random_ignition.clj

When using an ignition-mask raster GRIDFIRE’s chooses random ignition sites
assuming there is at least one cell that has a burnable fuel model number. When
given an ignition mask that does not have any valid ignition sites, the process
to choose an ignition point enters an infinite loop. This PR fixes this, by
preprocessing the valid ignition site during the load-inputs phase.
Closes GRID-172

GRID-172 Check for valid ignition-sites before running simulations

---

resources/upload_tarball.sh

Remove errors from logs when extracting tarball to geoserver:
`Cannot utime: Operation not permitted`
Closes GRID-174

GRID-174 Add --no-overwrite-dir option to tar extraction process
